baseURL = 'https://wjbmr.netlify.app/'
title = 'World Journal of Biomedical Research'
languageCode = 'en-us'
relativeURLs =  true

theme = 'wjbmr'

pluralizeListTitles = false 
preserveTaxonomyNames = true

[permalinks]
  issues = ':section/:06/:01/'
  articles = ':section/:06/:01/:title/'

[taxonomies]
  author = "authors"
  keyword = "keywords"